-- 004_additional_tables.sql
-- Additional tables for unmapped CSV files

-----------------------
-- DRAFT COMBINE STATS
-----------------------

CREATE TABLE draft_combine_stats (
    combine_stats_id   BIGSERIAL PRIMARY KEY,
    season_end_year    INTEGER,
    player_id          INTEGER REFERENCES players(player_id),
    player_name        TEXT,
    position           TEXT,
    height_wo_shoes    NUMERIC,
    height_w_shoes     NUMERIC,
    weight             NUMERIC,
    wingspan           NUMERIC,
    standing_reach     NUMERIC,
    body_fat_pct       NUMERIC,
    hand_length        NUMERIC,
    hand_width         NUMERIC,
    standing_vertical  NUMERIC,
    max_vertical       NUMERIC,
    lane_agility_time  NUMERIC,
    modified_lane_agility_time NUMERIC,
    three_quarter_sprint NUMERIC,
    bench_press        INTEGER,
    spot_fifteen_corner_left NUMERIC,
    spot_fifteen_break_left  NUMERIC,
    spot_fifteen_top_key     NUMERIC,
    spot_fifteen_break_right NUMERIC,
    spot_fifteen_corner_right NUMERIC,
    spot_college_corner_left  NUMERIC,
    spot_college_break_left   NUMERIC,
    spot_college_top_key      NUMERIC,
    spot_college_break_right  NUMERIC,
    spot_college_corner_right NUMERIC,
    off_drib_fifteen_break_left  NUMERIC,
    off_drib_fifteen_top_key     NUMERIC,
    off_drib_fifteen_break_right NUMERIC,
    off_drib_college_break_left  NUMERIC,
    off_drib_college_top_key     NUMERIC,
    off_drib_college_break_right NUMERIC,
    on_move_fifteen    NUMERIC,
    on_move_college    NUMERIC
);

CREATE INDEX draft_combine_stats_player_idx ON draft_combine_stats (player_id);
CREATE INDEX draft_combine_stats_season_idx ON draft_combine_stats (season_end_year);

-----------------------
-- GAME OFFICIALS
-----------------------

CREATE TABLE game_officials (
    game_id            TEXT NOT NULL REFERENCES games(game_id),
    official_id        TEXT NOT NULL,
    official_name      TEXT,
    jersey_num         TEXT,
    PRIMARY KEY (game_id, official_id)
);

CREATE INDEX game_officials_game_id_idx ON game_officials (game_id);
CREATE INDEX game_officials_official_id_idx ON game_officials (official_id);

-----------------------
-- PLAYER PLAY-BY-PLAY STATS
-----------------------

CREATE TABLE player_playbyplay_stats (
    seas_id            BIGINT PRIMARY KEY REFERENCES player_season(seas_id),
    bad_pass_tov       INTEGER,
    lost_ball_tov      INTEGER,
    off_foul_tov       INTEGER,
    shoot_foul_drawn   INTEGER,
    off_foul_drawn     INTEGER,
    pga                INTEGER,  -- Points generated by assists
    and1               INTEGER,
    blkd               INTEGER   -- Shots blocked
);

-----------------------
-- PLAYER SHOOTING STATS
-----------------------

CREATE TABLE player_shooting_stats (
    shooting_stats_id  BIGSERIAL PRIMARY KEY,
    seas_id            BIGINT REFERENCES player_season(seas_id),
    player_id          INTEGER REFERENCES players(player_id),
    season_end_year    INTEGER,
    team_abbrev        TEXT,
    age                INTEGER,
    -- Distance-based shooting
    pct_fga_2p         NUMERIC,
    pct_fga_0_3        NUMERIC,
    pct_fga_3_10       NUMERIC,
    pct_fga_10_16      NUMERIC,
    pct_fga_16_3p      NUMERIC,
    pct_fga_3p         NUMERIC,
    fg_pct_0_3         NUMERIC,
    fg_pct_3_10        NUMERIC,
    fg_pct_10_16       NUMERIC,
    fg_pct_16_3p       NUMERIC,
    -- Assisted vs unassisted
    pct_2p_assisted    NUMERIC,
    pct_3p_assisted    NUMERIC,
    pct_fg_assisted    NUMERIC,
    -- Dunks and layups
    dunk_pct_fga       NUMERIC,
    dunks_made         INTEGER,
    dunks_attempted    INTEGER,
    pct_3pa_corner     NUMERIC,
    fg_pct_corner_3    NUMERIC,
    -- Heaves
    heaves_att         INTEGER,
    heaves_made        INTEGER
);

CREATE INDEX player_shooting_stats_seas_id_idx ON player_shooting_stats (seas_id);
CREATE INDEX player_shooting_stats_player_season_idx 
    ON player_shooting_stats (player_id, season_end_year);

-----------------------
-- TEAM SUMMARIES
-----------------------

CREATE TABLE team_summaries (
    summary_id         BIGSERIAL PRIMARY KEY,
    team_season_id     BIGINT REFERENCES team_season(team_season_id),
    team_id            INTEGER REFERENCES teams(team_id),
    season_end_year    INTEGER,
    lg                 TEXT,
    wins               INTEGER,
    losses             INTEGER,
    win_pct            NUMERIC,
    finish             INTEGER,
    srs                NUMERIC,  -- Simple Rating System
    pace               NUMERIC,
    rel_pace           NUMERIC,
    ortg               NUMERIC,  -- Offensive Rating
    rel_ortg           NUMERIC,
    drtg               NUMERIC,  -- Defensive Rating
    rel_drtg           NUMERIC,
    playoffs           TEXT,
    coaches            TEXT
);

CREATE INDEX team_summaries_team_season_idx 
    ON team_summaries (team_id, season_end_year);
CREATE INDEX team_summaries_team_season_id_idx 
    ON team_summaries (team_season_id);
